phrases = [
    "Você abre seu diário e escreve sobre como acordou com o som suave dos pássaros, e a brisa fresca da manhã trouxe consigo o perfume das flores do campo.",
    "Você abre seu diário e escreve sobre a tarde que passou colhendo flores silvestres e sentindo a grama macia sob seus pés descalços. Há algo de mágico na simplicidade da natureza.",
    "Você abre seu diário e escreve sobre o momento em que preparava o chá com ervas frescas do seu jardim, percebendo a beleza dos pequenos detalhes que tornam a vida tão especial.",
    "Você abre seu diário e escreve sobre a luz do sol filtrada pelas árvores, criando sombras dançantes no chão da floresta, lembrando-lhe que a beleza pode ser encontrada nas coisas mais simples.",
    "Você abre seu diário e escreve sobre a serenidade de bordar à beira da lareira, sentindo uma profunda conexão com as tradições antigas e o estilo de vida rural.",
    "Você abre seu diário e escreve sobre como cuidar do jardim é terapêutico. Cada planta que floresce é um lembrete da paciência e do cuidado que cultivamos em nossas vidas.",
    "Você abre seu diário e escreve sobre como os dias são mais doces quando preenchidos com atividades simples, como fazer pão caseiro e ouvir o canto dos pássaros.",
    "Você abre seu diário e escreve sobre as noites na cabana, acolhedoras e tranquilas. O crepitar do fogo na lareira é a melodia perfeita para um coração em paz.",
    "Você abre seu diário e escreve sobre o momento em que se sentou à sombra de um carvalho antigo, lendo um livro enquanto a natureza sussurrava seus segredos ao seu redor.",
    "Você abre seu diário e escreve sobre como a vida no campo ensina a valorizar a calma e a beleza que existem no presente. Cada momento é um presente a ser apreciado.",
    "Você abre seu diário e escreve sobre como passou a manhã fazendo geleia de frutas frescas, sentindo o doce aroma se espalhar pela cozinha.",
    "Você abre seu diário e escreve sobre a caminhada pelo bosque, onde encontrou um riacho cristalino que parecia sussurrar segredos antigos.",
    "Você abre seu diário e escreve sobre a tarde que passou tricotando uma manta macia, cada ponto representando uma memória querida.",
    "Você abre seu diário e escreve sobre a visita ao mercado local, onde encontrou produtos frescos e artesanatos únicos.",
    "Você abre seu diário e escreve sobre o momento em que se sentou no alpendre, observando o pôr do sol tingir o céu de tons dourados e rosados.",
    "Você abre seu diário e escreve sobre o prazer de ler um livro clássico à sombra de uma árvore frondosa, ouvindo o som suave das folhas ao vento.",
    "Você abre seu diário e escreve sobre o aroma da lavanda que plantou no jardim, trazendo um senso de calma e serenidade.",
    "Você abre seu diário e escreve sobre o prazer de fazer uma torta caseira, desde amassar a massa até saborear o resultado final.",
    "Você abre seu diário e escreve sobre como decorou a casa com flores silvestres, enchendo os cômodos de cores vibrantes e vida.",
    "Você abre seu diário e escreve sobre a alegria de alimentar os animais da fazenda, sentindo a conexão com cada ser vivo.",
    "Você abre seu diário e escreve sobre a manhã passada ajudando os vizinhos a colher maçãs no pomar comunitário, compartilhando risadas e histórias antigas.",
    "Você abre seu diário e escreve sobre o piquenique à beira do lago com outros camponeses, onde cada um trouxe um prato caseiro para compartilhar.",
    "Você abre seu diário e escreve sobre a feira de trocas na aldeia, onde artesãos e agricultores se reuniram para trocar seus produtos e habilidades.",
    "Você abre seu diário e escreve sobre a tarde em que ajudou um vizinho a construir uma cerca, aprendendo novas habilidades e fortalecendo amizades.",
    "Você abre seu diário e escreve sobre a festa da colheita, onde dançou ao som de músicas tradicionais e celebrou a abundância com os outros moradores.",
    "Você abre seu diário e escreve sobre a reunião ao redor da fogueira, onde ouviu histórias de tempos passados e compartilhou risadas com amigos.",
    "Você abre seu diário e escreve sobre a visita à feira de artesanato local, onde conheceu artesãos talentosos e aprendeu sobre suas técnicas.",
    "Você abre seu diário e escreve sobre o mutirão para plantar árvores na praça da aldeia, sentindo a alegria de contribuir para o futuro da comunidade.",
    "Você abre seu diário e escreve sobre a tarde em que preparou um chá para os vizinhos, desfrutando de uma conversa agradável e fortalecendo laços.",
    "Você abre seu diário e escreve sobre a caminhada com outros camponeses pelas trilhas da floresta, apreciando a natureza e a companhia um do outro."
]


fortunes = [
    "Sorte do dia: Hoje você encontrará paz nos sons da natureza.",
    "Sorte do dia: Pequenos momentos trarão grandes alegrias hoje.",
    "Sorte do dia: A simplicidade será sua maior aliada.",
    "Sorte do dia: Beleza inesperada surgirá em seu caminho.",
    "Sorte do dia: Conexões profundas enriquecerão seu dia.",
    "Sorte do dia: Sua paciência será recompensada hoje.",
    "Sorte do dia: Encontre doçura nas tarefas simples.",
    "Sorte do dia: A tranquilidade estará ao seu alcance.",
    "Sorte do dia: A sabedoria chegará até você em momentos de quietude.",
    "Sorte do dia: Aprecie cada momento, pois eles são únicos.",
    "Sorte do dia: Hoje, você saboreará os frutos do seu trabalho.",
    "Sorte do dia: Novas descobertas trarão alegria ao seu dia.",
    "Sorte do dia: Seus esforços de hoje criarão conforto para o futuro.",
    "Sorte do dia: Conexões locais enriquecerão sua vida hoje.",
    "Sorte do dia: A beleza do entardecer trará paz ao seu coração.",
    "Sorte do dia: Encontre inspiração nas palavras dos sábios de antigamente.",
    "Sorte do dia: Aromas calmantes irão transformar seu ambiente.",
    "Sorte do dia: A satisfação estará nos detalhes das suas criações.",
    "Sorte do dia: A natureza trará alegria e cor ao seu espaço.",
    "Sorte do dia: A interação com os animais trará momentos de pura felicidade.",
    "Sorte do dia: A colaboração trará alegria e união ao seu dia.",
    "Sorte do dia: O compartilhamento de alimentos fortalecerá os laços de amizade.",
    "Sorte do dia: Novas conexões trarão oportunidades valiosas.",
    "Sorte do dia: Ajudar os outros trará uma sensação de realização e comunidade.",
    "Sorte do dia: Celebrações comunitárias encherão seu coração de alegria.",
    "Sorte do dia: As histórias compartilhadas fortalecerão os vínculos de amizade.",
    "Sorte do dia: Aprender com os outros enriquecerá sua perspectiva.",
    "Sorte do dia: Seus esforços comunitários trarão benefícios duradouros.",
    "Sorte do dia: Pequenos gestos de hospitalidade criarão grandes memórias.",
    "Sorte do dia: A camaradagem ao ar livre renovará seu espírito."
]

